import apart from '../img/apart.jpg';

export const items = [
  {
    id: 1,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 2,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 3,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 4,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 5,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 6,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 7,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 8,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 9,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 10,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 11,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 12,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
  {
    id: 13,
    imgSrc: apart,
    imgAlt: 'name',
    title: 'Двустаен Апартамент',
    sqm: '60',
    rooms: '2',
    price: '1000',
    address: 'София, ул. Люлин 1',
  },
];
